version: '3.8'

services:
    php:
        image: php:8.1-fpm
        build:
            dockerfile: docker/php/Dockerfile
        user: "1000:1000"
        volumes:
            -   './:/var/www/html'
            - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
        command: ["sh", "-c", "php-fpm"]
        networks:
            - laravel

    nginx:
        image: nginx:latest
        ports:
            - 8000:80
        volumes:
            - './:/var/www/html'
            - './docker/nginx/conf.d:/etc/nginx/conf.d'
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=12345Qq=
        ports:
            -   3306:3306
        volumes:
            - './docker/volume/mysql:/var/lib/mysql'
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            -   9090:80
        environment:
            -   PMA_HOST=mysql
            -   PMA_PORT=3306
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
